name: Deploy Pull Request to GitHub Pages

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        run: |
          export BRANCH_NAME=${GITHUB_REF#refs/heads/}
          npm run build
          git checkout gh-pages
          rm -rf *
          cp -r ../build/* .
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "Deploy $BRANCH_NAME to GitHub Pages"
          git push origin gh-pages
